### ISSUE TITLE
Contribution and Cleaning 

### ISSUE THREAD

**Issue by Pandz18** [The4thDimension/Cpp-Basic-program#1]
Hey , 

I was wondering if I could contribute to the repository , do you have a list of programs that you would like me to add or is it everyone for himself ?

Also I was wondering if I could arrange all the files and to clean the repository ?

Cheers

**Comment by The4thDimension** [comment]
Hyy,
Thanks for showing interest. I'm new to github and am trying to get used to all this. Of course, you're welcome to contribute. I'm just a student, with quite an interest in programming. Anyway, go crazy on the repository. mi casa su casa. Cheers.

**Comment by Pandz18** [comment]
Hey , 

Me too , I’m a student and I’m learning C++ atm . I’m new to Github too .

Haha thanks man , cheers
